version: '3'
networks:
  base_network:
services:
  apache:
    container_name: apache
    build:
      context: .  # Le chemin vers le répertoire contenant le Dockerfile
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - base_network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      # MYSQL_DATABASE: wordpress
      # MYSQL_USER: wordpress
      # MYSQL_PASSWORD: wordpress_password
    ports:
      - "3306:3306" 
    networks:
      - base_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - base_network